export const dictionary: any = {
  en: {
    homeNav: "For Homes",
    businessNav: "For Busniess",
    projectsNav: "Projects",
    contactNav: "Contact",
    homeHeader: "Home",
    heroExperience: "10+ YEARS OF EXPERIENCE",
    basedSolarHero: "Based Solar:",
    heroHeader: "Your Gateway to Clean, Cost-Efficient Energy Solutions",
    heroP:
      "Curious about the potential of solar energy for your home or business? Get a free quote from Based Solar today and discover how you can save money and the planet.",
    getAQuote: "Get a Quote",
    aboutUs: "About Us",
    aboutUsParagraph:
      "Welcome to Based Solar: Your Gateway to Clean, Cost-Efficient Energy Solutions.Our green power services at Based Solar offer clean, sustainable energy solutions for businesses and homeowners. We provide state-of-the-art photovoltaic systems, energy efficiency, and a greener future, all while reducing costs and environmental impact. Empower your future with our premier photovoltaic systems.",
    letsGoSolar: "Let's go solar today!",
    reducedBill: "Reduced bills by up to 70%",
    reducedBillP:
      "Photovoltaic systems use sunlight to produce electricity. Appliances in homes and other users can directly use the energy that is produced. It can also be retrieved and stored into the national network.",
    energy: "Energy Self-Sufficiency",
    energyP:
      "Regarding the energy bill, photovoltaic panels provide stability and predictability in the current climate where bills are expensive and vary annually.",
    whatDoWeOffer: " What do we offer ",
    toYou: " to you",
    forHouses: "For Houses",
    forHousesP:
      "Elevate your home with our tailored solutions, providing unmatched quality and reliability.",
    forBusiness: "For Businesses",
    forBusinessP:
      "Empower your business with our specialized services, tailored to meet the unique needs of commercial spaces.",
    forAssociation: "For Housing Associations",
    forAssociationP:
      "Our solutions for housing associations focus on sustainable, community-centric initiatives to enhance the well-being of residents.",
    gurantee: "30 Years Guarantee",
    guranteeP:
      "With a solid 30-year guarantee, our products and services are built to last, providing you with long-term peace of mind and satisfaction.",
    demand: "Demand Response",
    demandP:
      "Our demand response solutions empower you to manage and optimize energy usage, ensuring efficiency and cost-effectiveness in real-time.",
    capacity: "Capacity Reserve",
    capacityP:
      "We offer reliable solutions to meet peak demand, ensuring a steady and resilient power supply when you need it the most.",
    projects: "Projects",
    projectsP: "Take a look at some of our completed projects.",
    viewProjects: "View all projects",
    getInTouch: "Empower your future with our premier photovoltaic systems",
    getInTouchP:
      "Curious about the potential of solar energy for your home or business? Get a free quote from Based Solar today and discover how you can save money and the planet.",
    contactUs: "Contact Us (Bulgaria, Sofia)",
    phone: "Phone",
    rights: "2023 Based Solar. All Rights Reserved",
    privacyPolicy: "Privacy Policy",
    poweredBy: "Powered by",
    welcome: "Welcome",
    menu: "Menu",
    getInTouchText: "Get in touch",
    keepScrolling: "Keep scrolling to view projects",
    letUsKnow: "Let us know more about",
    your: "your",
    solarPlan: "solar plan",
    yourName: "Your name",
    yourEmail: "Your email",
    yourProject: "Tell us about your project",
    submit: "Submit",
    sending: "Sending...",
    openSlider: "Click image to open slider",
    homesHeading:
      "A solar power plant on a private property is a profitable investment",
    homesP:
      "With a solar power plant, you can start producing electricity right away, save money on energy bills, and even profit from selling excess power. The clean energy source of the future is solar electricity.",
    homesHeading2: "The solar power plant owned by the household",
    homesP2:
      "Establishing a solar power system at the household level is a smart investment with a range of tangible benefits. Let's explore the advantages of having a residential solar power plant in more detail:",
    businessHeading: "Lower energy expenses for your business with solar power",
    businessP:
      "The yield of the solar power plant is evident in the electricity bill savings. The electricity generated by solar power plants is environmentally friendly and represents the energy source of the future.",
    businessHeading2: "An investment that pays off is the solar power plant.",
    businessP2:
      "Establishing a solar power system at the household level is a smart investment with a range of tangible benefits. Let's explore the advantages of having a residential solar power plant in more detail:",
    reducedEnergyTitle: "Reduced Energy Bills",
    reducedEnergyDesc:
      "A residential solar power plant allows homeowners to generate their electricity, leading to a significant reduction in monthly energy bills. By harnessing the power of the sun, households can offset or even eliminate their dependence on traditional utility providers.",
    longTermInvestmentTitle: "Long-Term Investment",
    longTermInvestmentDesc:
      "While the initial investment in a solar power system might seem significant, it's essential to view it as a long-term investment. Over time, the financial savings accrued from lower energy bills can surpass the initial setup costs, potentially resulting in a profitable venture.",
    increasedPropertyValueTitle: "Increased Property Value",
    increasedPropertyValueDesc:
      "Homes equipped with solar power systems tend to have higher property values. The presence of a sustainable and energy-efficient feature is attractive to potential buyers and reflects positively on the overall value of the property. This can be a key selling point in the real estate market.",
    energyIndependenceTitle: "Energy Independence",
    energyIndependenceDesc:
      "Households with solar power systems gain a degree of energy independence. This is especially valuable during power outages or disruptions to the traditional grid. With a reliable solar energy source, homeowners can ensure a continuous power supply for essential appliances.",
    lowMaintenanceCostsTitle: "Low Maintenance Costs",
    lowMaintenanceCostsDesc:
      "Solar power systems generally have low maintenance costs. Regular cleaning and occasional checks are usually sufficient to keep the system running efficiently. This contributes to the overall cost-effectiveness of residential solar power installations.",
  },
  bg: {
    homeNav: "За домове",
    businessNav: "За бизнеси",
    projectsNav: "Проекти",
    contactNav: "Контакти",
    homeHeader: "Home",
    heroExperience: "10+ Години Опит",
    basedSolarHero: "Басед Солар:",
    heroHeader: "Вашият портал към чисти и рентабилни енергийни решения",
    heroP:
      "Любопитни ли сте за потенциала на слънчевата енергия за вашия дом или бизнес? Получете безплатна оферта от Басед Солар днес и открийте как можете да спестите пари и да спасите планетата.",
    getAQuote: "Пратете запитване",
    aboutUs: "За нас",
    aboutUsParagraph:
      "Добре дошли в Басед Солар: Вашият портал към чисти и рентабилни енергийни решения. Нашите услуги за зелена енергия в Басед Солар предлагат чисти, устойчиви енергийни решения за фирми и собственици на имоти. Ние предлагаме най-съвременни фотоволтаични системи, енергийна ефективност и по-зелено бъдеще, като същевременно намаляваме разходите и въздействието върху околната среда. Осигурете бъдещето си с нашите първокласни фотоволтаични системи.",
    letsGoSolar: "Хайде да използваме слънцето днес!",
    reducedBill: "Намалени сметки с до 70%",
    reducedBillP:
      "Фотоволтаичните системи използват слънчева светлина за производство на електричество. Уредите в домовете и другите потребители могат директно да използват произведената енергия. Може също да бъде извлечен и съхранен в националната мрежа.",
    energy: "Енергийна самодостатъчност",
    energyP:
      "Що се отнася до сметката за енергия, фотоволтаичните системи осигуряват стабилност и предсказуемост в настоящия климат, където сметките са скъпи и варират всяка година.",
    whatDoWeOffer: " Какво предлагаме ",
    toYou: " на теб",
    forHouses: "За домове",
    forHousesP:
      "Подобрете дома си с нашите персонализирани решения, осигуряващи несравнимо качество и надеждност.",
    forBusiness: "За бизнеси",
    forBusinessP:
      "Дайте възможност на бизнеса си с нашите специализирани услуги, пригодени да отговорят на уникалните нужди на търговските пространства.",
    forAssociation: "За жилищни асоциации",
    forAssociationP:
      "Нашите решения за жилищни асоциации се фокусират върху устойчиви, ориентирани към общността инициативи за подобряване на благосъстоянието на жителите.",
    gurantee: "25 Години Гаранция",
    guranteeP:
      "Със солидна 25-годишна гаранция, нашите продукти и услуги са създадени да издържат, осигурявайки ви дългосрочно спокойствие и удовлетворение.",
    demand: "Отговаряме на търсенето",
    demandP:
      "Нашите решения за отговор на търсенето ви дават възможност да управлявате и оптимизирате потреблението на енергия, като гарантирате ефективност и рентабилност в реално време.",
    capacity: "Резервен капацитет",
    capacityP:
      "Ние предлагаме надеждни решения за посрещане на пиково търсене, осигурявайки стабилно и устойчиво захранване, когато имате най-голяма нужда от него.",
    projects: "Проекти",
    projectsP: "Разгледайте някои от нашите завършени проекти.",
    viewProjects: "Вижте всички проекти",
    getInTouch: "Осигурете бъдещето си с нашите първокласни фотоволтаични системи",
    getInTouchP:
      "Любопитни ли сте за потенциала на слънчевата енергия за вашия дом или бизнес? Получете безплатна оферта от Басед Солар днес и открийте как можете да спестите пари и планетата.",
    contactUs: "Свържете се с нас (България, София)",
    phone: "Телефон",
    rights: "2023 Based Solar. All Rights Reserved",
    privacyPolicy: "Политика за поверителност",
    poweredBy: "Powered by",
    welcome: "Начало",
    menu: "Меню",
    getInTouchText: "Свържете се",
    keepScrolling: "Продължете да скролвате, за да видите проекти",
    letUsKnow: "Уведомете ни повече за",
    your: "Вашият",
    solarPlan: "соларен план",
    yourName: "Твоето име",
    yourEmail: "Твоят имейл",
    yourProject: "Разкажете ни за вашата идея",
    submit: "Изпрати",
    sending: "Изпращане...",
    openSlider: "Кликнете върху изображението, за да отворите галерията",
    homesHeading:
      "Слънчева електроцентрала в частен имот е изгодна инвестиция",
    homesP:
      "Със слънчева електроцентрала можете да започнете да произвеждате електричество веднага, да спестите пари от сметки за енергия и дори да спечелите от продажбата на излишната енергия. Източникът на чиста енергия на бъдещето е слънчевата енергия.",
    homesHeading2: "Слънчевата електроцентрала е собственост на домакинството",
    homesP2:
      "Създаването на слънчева енергийна система на ниво домакинство е интелигентна инвестиция с набор от осезаеми ползи. Нека проучим по-подробно предимствата от наличието на слънчева електроцентрала за жилищни сгради:",
    businessHeading: "По-ниски разходи за енергия за вашия бизнес със слънчева енергия",
    businessP:
      "Доходността от слънчевата централа се вижда в спестяванията от сметки за електроенергия. Електричеството, генерирано от слънчеви електроцентрали, е екологично чисто и представлява енергийният източник на бъдещето.",
    businessHeading2: "Инвестиция, която се изплаща от слънчевата централа.",
    businessP2:
      "Интегрирането на слънчева енергийна система на корпоративно ниво е стратегическа инвестиция с множество осезаеми предимства. Нека разгледаме по-подробно ползите от прилагането на комерсиално решение за слънчева енергия:",
    reducedEnergyTitle: "Намалени сметки за ток",
    reducedEnergyDesc:
      "Жилищната слънчева електроцентрала позволява на собствениците на жилища да генерират своята електроенергия, което води до значително намаляване на месечните сметки за енергия. Използвайки силата на слънцето, домакинствата могат да компенсират или дори да премахнат зависимостта си от традиционните доставчици на комунални услуги.",
    longTermInvestmentTitle: "Дългосрочна инвестиция",
    longTermInvestmentDesc:
      "Докато първоначалната инвестиция в слънчева енергийна система може да изглежда значителна, важно е да я разглеждате като дългосрочна инвестиция. С течение на времето финансовите спестявания, натрупани от по-ниски сметки за енергия, могат да надминат първоначалните разходи за настройка, което потенциално ще доведе до печелившо начинание.",
    increasedPropertyValueTitle: "Повишена стойност на имота",
    increasedPropertyValueDesc:
      "Имотите, оборудвани със слънчеви енергийни системи, обикновено имат по-висока стойност. Наличието на устойчива и енергийно ефективна характеристика е привлекателно за потенциалните купувачи и рефлектира положително върху общата стойност на имота. Това може да бъде ключова точка за продажба на пазара на недвижими имоти.",
    energyIndependenceTitle: "Енергийна независимост",
    energyIndependenceDesc:
      "Имотите със слънчеви енергийни системи получават известна степен на енергийна независимост. Това е особено ценно при прекъсване на електрозахранването или смущения в традиционната мрежа. С надежден източник на слънчева енергия собствениците на жилища могат да осигурят непрекъснато електрозахранване за основните уреди.",
    lowMaintenanceCostsTitle: "Ниски разходи за поддръжка",
    lowMaintenanceCostsDesc:
      "Слънчевите енергийни системи обикновено имат ниски разходи за поддръжка. Редовното почистване и периодичните проверки обикновено са достатъчни, за да поддържате системата работеща ефективно. Това допринася за общата рентабилност на жилищните слънчеви енергийни инсталации.",
  },
};
