import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

import "./globals.css";
import Header from "@/components/shared/Header";
import { AppProvider } from "@/context/AppContext";
import Footer from "@/components/shared/Footer";

const nunito_sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Based Solar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang ?? "en"}>
      <AppProvider>
        <body>
          <Header />
          <main className={`${nunito_sans.className} scroll-smooth`}>
            {children}
          </main>
          <Footer />
        </body>
      </AppProvider>
    </html>
  );
}
